Edit Posts
NewForce-Cohort-5/tabloidmvc-the-daily-debuggers pull request #5
Opened 2022-03-02 18:44 UTC by nicholasvperry

# Description
Added the ability to edit posts. When the user navigates to posts menu they have the ability to click the edit button. There is also an edit button inside the details view. User can edit post and save and view edited post.

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. git add and git commit all changes in your current branch.
2. git checkout main
3. git fetch -a
4. git checkout edit-post-np
5. Navigate to the root directory for this repo (directory-to)/tabloidmvc-the-daily-debuggers
6. Start TabloidMVC.sln
7. Make sure your db is created with seed data (Skip to 9 if this is already done)
8. Run [01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-daily-debuggers/blob/main/SQL/01_TabloidMVC_Create_DB.sql) and [02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-daily-debuggers/blob/main/SQL/02_TabloidMVC_Seed_Data.sql) queries in Visual Studio
9. Start the server in Debug Mode F5
10. Log in as admin admin@example.com (if not already logged in as admin)
11. Navigate to the posts link
12. Select edit symbol beside post or click view post then edit symbol
13. Edit post
14. Click save
15. You will see the updated post

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

2022-03-02 19:04 UTC, cbgriffith approved these changes
Edit works perfectly.

2022-03-02 19:18 UTC, andy-birt requested changes
It looks good. The only concern is mixing the delete ticket with the edit. We got to have a PR for each ticket.

2022-03-02 19:18 UTC, andy-birt commented on TabloidMVC/Controllers/PostController.cs
> +            posts.Sort((y, x) => DateTime.Compare((DateTime)x.PublishDateTime, (DateTime)y.PublishDateTime));
I don't think you need this line now that you're sorting the posts in the sql command.

2022-03-02 19:18 UTC, andy-birt commented on TabloidMVC/Controllers/PostController.cs
> +        // GET: PostController/Delete
Delete is a separate ticket. You may comment out the delete functionality and put it in a different pr. I'm sure it's already working.

2022-03-02 19:18 UTC, andy-birt commented on TabloidMVC/Repositories/PostRepository.cs
> +        public void DeletePost(int postId)
same thing here as previous comment.

2022-03-02 20:47 UTC, andy-birt approved these changes

2022-03-02 21:40 UTC, jordan-castelloe requested changes
Hey! Generally this looks great. I did find one bug-- the "Header Image URL" form field is not required, but if you leave that field blank I get the following exception: 
```
An unhandled exception occurred while processing the request.
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'TabloidMVC.Models.Post', but this ViewDataDictionary instance requires a model item of type 'TabloidMVC.Models.ViewModels.PostCreateViewModel'.
```
Your options are to either make that field required (if you actually want it to be required-- maybe discuss with the team!) or write in some conditional logic in your controller so that it doesn't try to insert null values into the database. When you've made the fix, let me know and I'll make a final pass!

2022-03-03 20:47 UTC, jordan-castelloe commented
@nicholasvperry checking in on this-- did you get a chance to push up these changes? Want me to make another pass?

2022-03-04 14:28 UTC, nicholasvperry commented
Fixed "Header Image URL" null issue. Edit will now allow with a null value.

2022-03-04 15:33 UTC, jordan-castelloe approved these changes

2022-03-04 15:53 UTC, merged